server:
  port: 10086
spring:
  application:
    name: leyou-register
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    register-with-eureka: false #服务注册中心也会将自己作为客户端来尝试注册自己,为true（默认）时自动生效
    fetch-registry: false #检索服务选项，当设置为True(默认值)时，会进行服务检索,注册中心不负责检索服务
