server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq: #配置rabbitmaq
    host: 112.124.46.10
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4Fch3dZVRvJDnhKjZ5Hy # 你自己的accessKeyId
    accessKeySecret: xj6FzPcrfGVW3eBjzgiMdAkHGGNaD6 # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_180345132 # 模板名称